import { AuthContextProvider } from "../../context/AuthContext";
import { ChatContextProvider } from "../../context/ChatContext";
import "./globals.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-raleway">
        <AuthContextProvider>
          <ChatContextProvider>{children}</ChatContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
